### ISSUE TITLE
responsive menu

### ISSUE THREAD

**Issue by JayArghArgh** [LindaHlubi/Project-1#8]
check whhy menu is showing both pull out and normal when in tablet mode.

**Comment by blakestickland** [comment]
I think I have the solution. Tried it out in Inspector and will use this as an opportunity for me to create a new branch and push to the project.

**Comment by blakestickland** [comment]
Menu responsiveness on medium-sized screens (eg. tablets) working --> dropdown menu appears for smaller screen widths, and standard header menu appears for larger and x-large screens.
